# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/REV/VivadoProjects/DWT_2F_32bit_256x256/DWT.srcs/sources_1/ip/blk_mem_gen_dual_256x32_1/blk_mem_gen_dual_256x32.xci
# IP: The module: 'blk_mem_gen_dual_256x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/REV/VivadoProjects/DWT_2F_32bit_256x256/DWT.srcs/sources_1/ip/blk_mem_gen_dual_256x32_1/blk_mem_gen_dual_256x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_dual_256x32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/REV/VivadoProjects/DWT_2F_32bit_256x256/DWT.srcs/sources_1/ip/blk_mem_gen_dual_256x32_1/blk_mem_gen_dual_256x32.xci
# IP: The module: 'blk_mem_gen_dual_256x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/REV/VivadoProjects/DWT_2F_32bit_256x256/DWT.srcs/sources_1/ip/blk_mem_gen_dual_256x32_1/blk_mem_gen_dual_256x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_dual_256x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
