# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints_1.xdc

# IP: ip/cordic_0/cordic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet
